Froyolo/config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'posts#index'
  get 'show_all' => 'posts#show_all'
  
  get 'filter' => 'posts#filter'
  post 'filter_results' => 'posts#filter_results'
  
  post 'increment' => 'posts#increment'
  post 'decrement' => 'posts#decrement'
  
  post 'find_importance' => 'posts#find_importance'
  get 'find_importance' => 'posts#find_importance'
  

end

Froyolo/app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  
  class_attribute :importance 
  class_attribute :age
  class_attribute :ageadjustedscore
end

Froyolo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

Froyolo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  require 'open-uri'

  respond_to :json
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def find_importance


    @posts = Post.where("xcoord > ?", search_params[:minx]).where("xcoord < ?", search_params[:maxx])
    @posts = @posts.where("ycoord > ?", search_params[:miny]).where("ycoord < ?", search_params[:maxy])

    lowest_possible_value = -3
    sum_importance = 0
    totalage = 0
    votespersecond = 1 / 36000

    @posts.each do |p|
      p.age = (Time.zone.now - p.created_at) * votespersecond
      totalage += p.age
    end

    @posts.each do |p|
      if p.age / totalage > 0.5
        p.ageadjustedscore = p.score - p.age * 2.0
      else
        p.ageadjustedscore = p.score - p.age / 2.0
      end
    end

    @posts.each do |p|
      sum_importance += (p.ageadjustedscore - lowest_possible_value)
    lowest_possible_value = -3
    @posts = Post.all
    sum_importance = 0
    totalage = 0
    
    @posts.each do |p|
      p.age = (Time.zone.now - p.created_at) / 3600 
      totalage += p.age

    end

    @posts.each do |p|

      if p.ageadjustedscore < lowest_possible_value + 1
        p.importance = 0
      else
        p.importance = 100 / 93.41 * (1.0 - Math.exp( -1 * (-1.0 * lowest_possible_value + p.ageadjustedscore) / sum_importance * Math.exp(1)))
      end
    end

      if p.age / totalage > 0.5
        p.ageadjustedscore = p.score - p.age * 2.0
      else
        p.ageadjustedscore = p.score - p.age / 2.0
      end
    end
    
    @posts.each do |p|
      sum_importance += (p.ageadjustedscore - lowest_possible_value)
    end
    
    @posts.each do |p|
      if p.ageadjustedscore < lowest_possible_value + 1
        p.importance = 0
      else
        p.importance = 100 / 93.41 * (1.0 - Math.exp( -1 * (-1.0 * lowest_possible_value + p.ageadjustedscore) / sum_importance * Math.exp(1))) 
      end
    end  
    @posts
  end

  #POST /increment/1.json
  def increment
    @post = Post.find(change_votes_params[:post_id])
    @post.score = @post.score + 1


    respond_to do |format|
      if @post.save
        format.html {
          redirect_to @post, notice: 'Post was successfully updated.' 
          }
        format.json {
          render json: @post 
          }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  #POST /decrement/1.json
  def decrement
    @post = Post.find(change_votes_params[:post_id])
    @post.score = @post.score - 1
    respond_to do |format|
      if @post.save
        format.html {
          redirect_to @post, notice: 'Post was successfully updated.' 
          }
        format.json {
          render json: @post 
          }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def filter
  end

  def filter_results

    @posts = Post.where("xcoord > ?", search_params[:minx]).where("xcoord < ?", search_params[:maxx])
    @posts = @posts.where("ycoord > ?", search_params[:miny]).where("ycoord < ?", search_params[:maxy])

  end


  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def show_all
    @posts = Post.all
    @post = Post.first
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.score = 0



    if(post_params[:image] == nil)
      path = "#{Rails.root}/public/uploads/post/image/#{@post.id}/image.jpg"
      File.open(path, "wb") do |f|
        f.write(Base64.decode64(@post.imagedata))
      end
      @post.image = File.open(path)
    else
      @post.imagedata = Base64.encode64(File.open(@post.image.path).read)
    end

    respond_to do |format|
      if @post.save
        format.html {
          redirect_to @post, notice: 'Post was successfully created.' 
          }
        format.json {
          render json: @post 
          }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:xcoord, :ycoord, :altitude, :horizontalaccuracy, :verticalaccuracy, :image, :imagedata)
  end

  def search_params
    params.permit(:minx, :maxx, :miny, :maxy)
  end

  def change_votes_params
    params.permit(:post_id)
  end

end

Froyolo/app/helpers/application_helper.rb
module ApplicationHelper
end

Froyolo/app/helpers/posts_helper.rb
module PostsHelper
end

Froyolo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Froyolo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Froyolo/app/views/posts/_form.html.erb
<%= form_for(@post, format: :json) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xcoord %><br>
    <%= f.text_field :xcoord %>
  </div>
  <div class="field">
    <%= f.label :ycoord %><br>
    <%= f.text_field :ycoord %>
  </div>
  <div class="field">
    <%= f.label :altitude %><br>
    <%= f.text_field :altitude %>
  </div>
<div>
  <%= f.label :image %>
  <%= f.file_field :image %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Froyolo/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

Froyolo/app/views/posts/filter.html.erb
<%= form_tag(filter_results_path(format: "json"), method: "post", id: "search-form") do %>
<%= label_tag "Min X-Coord" %>
<%= text_field_tag :minx, nil, placeholder: "Search posts" %><br>
<%= label_tag "Max X-Coord" %>
<%= text_field_tag :maxx, nil, placeholder: "Search posts" %><br>
<%= label_tag "Min Y-Coord" %>
<%= text_field_tag :miny, nil, placeholder: "Search posts" %><br>
<%= label_tag "Max Y-Coord" %>
<%= text_field_tag :maxy, nil, placeholder: "Search posts" %><br>
<%= submit_tag "Search", name: nil %>
<% end %>

Froyolo/app/views/posts/find_importance.html.erb
<% @posts.each do |p| %>
<p>coords: <%=p.xcoord%>x<%=p.ycoord%> importance: <%=p.importance%></p>
<% end %>

Froyolo/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Xcoord</th>
      <th>Ycoord</th> 
      <th>Score!</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td><%= post.xcoord %></td>
      <td><%= post.ycoord %></td>
      <td><%= post.altitude %></td>
      <td><%= post.score %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %><br>
<%= link_to 'Filter', filter_path %>

Froyolo/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

Froyolo/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @post.image.url %>

<p>
  <strong>Xcoord:</strong>
  <%= @post.xcoord %>
</p>

<p>
  <strong>Ycoord:</strong>
  <%= @post.ycoord %>
</p>

<p>
  <strong>Altitude:</strong>
  <%= @post.altitude %>
</p>



<p>
  <strong>Score:</strong>
  <%= @post.score %>
</p>

<%= form_tag(increment_path(format: "json"), method: "post", id: "search-form") do %>
<%= label_tag "Post ID" %>
<%= text_field_tag :post_id, @post.id, placeholder: @post.id %><br>
<%= submit_tag "Increment", name: nil %>
<% end %>

<%= form_tag(decrement_path(format: "json"), method: "post", id: "search-form") do %>
<%= label_tag "Post ID" %>
<%= text_field_tag :post_id, @post.id, placeholder: @post.id %><br>
<%= submit_tag "Decrement", name: nil %>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>